namespace UniOne.Models;

public class ApiErrorData
{
    public int Code { get; set; }
    public string Meaning { get; set; }

    public ApiErrorData(int code, string meaning)
    {
        Code = code;
        Meaning = meaning;
    }

    public static string GetError(int code)
    {
        string result = "";
        try
        {
            result = GetErrorCodes().FirstOrDefault(e => e.Code == code)!.Meaning;
        }
        catch
        {
            result = "No error code found ( " + code + " )";
        }

        return result;
    }
    
    public static List<ApiErrorData> GetErrorCodes()
    {
        List<ApiErrorData> errorCodes = new List<ApiErrorData>
        {
            new ApiErrorData(101, "API key is not passed or empty. Make sure you have passed correct X-API-KEY header or ‘api_key’ JSON parameter."), 
            new ApiErrorData(102, "Invalid key ‘$apiKey’. Use correct user API-key or project API key."), 
            new ApiErrorData(105, "API is turned OFF. You can turn API on here."), 
            new ApiErrorData(106, "User is inactive. To solve this problem, contact support."), 
            new ApiErrorData(111, "JSON parsing error. Check your JSON request syntax."), 
            new ApiErrorData(114, "The user has not been found.Please send the request to the host you have been registered at, us1.unione.io or eu1.unione.io. "), 
            new ApiErrorData(118, "No DNS TXT records found. Add a DNS verification record to your domain with values returned by domain/get-dns-records."), 
            new ApiErrorData(120, "Internal DKIM validation error. Please contact support."), 
            new ApiErrorData(121, "Timeout searching domain. DNS request has timed out. Please make sure your DNS provider is online and try again later."), 
            new ApiErrorData(122, "DKIM record not found (almost the same as 120). Please add to your domain a DKIM record with key returned by domain/get-dns-records method."), 
            new ApiErrorData(123, "DKIM record malformed. You should properly setup DKIM for your domain."), 
            new ApiErrorData(124, "DKIM record does not match expected. Seems like you have changed the record. While it’s technically correct, it doesn’t match the one we expect. You should use DKIM key returned by domain/get-dns-records method."), 
            new ApiErrorData(125, "There are several different DKIM keys in the DNS entry. Please setup the DKIM record for your domain properly."), 
            new ApiErrorData(126, "There are other non-DKIM record types present in the DNS record. Please add a DKIM record for your domain with a key returned by domain/get-dns-records API method."), 
            new ApiErrorData(127, "Main domain DKIM record limit reached. >A maximum of 10 DKIM records are allowed per primary domain."), 
            new ApiErrorData(129, "Unknown DKIM validation error with reason distinct to the ones from 120-124 errors. Please check that you have correctly added a DKIM record with key returned by domain/get-dns-records method and try again. Please contact support if the error still occurs."), 
            new ApiErrorData(130, "The domain is not allowed according to Registry policy. Please use another domain."), 
            new ApiErrorData(150, "Аn unknown internal error occurred. Unknown error occurred. Please try again later or contact support."), 
            new ApiErrorData(199, "Request is too large. The data in request should be no more than 10 MB."), 
            new ApiErrorData(201, "The message body is missing. Check that your message body is being passed properly."), 
            new ApiErrorData(202, "Sender email is missing. Enter the sender email."), 
            new ApiErrorData(203, "Email subject is missing. Enter the subject."), 
            new ApiErrorData(204, "Email recipients are passed improperly. Make sure that the recipient’s list is passed as an array where each recipient is an array with obligatory ‘email’ parameter."), 
            new ApiErrorData(205, "Invalid sender email. Make sure the parameter is passed properly."), 
            new ApiErrorData(206, "Sender email is not verified. To avoid this error please use an email on a verified domain."), 
            new ApiErrorData(207, "MIME file type is incorrect. Check the file and the file type again."), 
            new ApiErrorData(208, "Invalid attachment filename. Forbidden symbol ‘$symbol’. Rename files with the forbidden symbols."), 
            new ApiErrorData(209, "The attached file names are duplicated. Rename files with the same names."), 
            new ApiErrorData(210, "Inline attachment names are duplicated. Rename files with the same names."), 
            new ApiErrorData(211, "Invalid inline attachment filename. Forbidden symbol ‘$symbol’. Rename files with the forbidden symbols."), 
            new ApiErrorData(212, "Recipients passed improperly (‘substitutions’ array is not set). The possible maximum substitutions number has been exceeded or substitutions have incorrect filetype (string/integer is allowed)."), 
            new ApiErrorData(213, "Invalid or non-existent custom_backend_id. Please enter a valid ‘custom_backend_id’ parameter."), 
            new ApiErrorData(215, "The user is not allowed to send. Try contacting support."), 
            new ApiErrorData(216, "Recipients passed improperly. ‘Metadata’ value should be a string or integer. Array for ‘metadata’ key is expected."), 
            new ApiErrorData(217, "Too many metadata fields passed. Maximum 10 metadata fields allowed."), 
            new ApiErrorData(218, "Recipients passed improperly. Metadata key length should be less than 64."), 
            new ApiErrorData(219, "Recipients passed improperly. Metadata value length should less than 1024."), 
            new ApiErrorData(220, "Metadata key should not be blank. Make sure the metadata key is passed."), 
            new ApiErrorData(221, "Thetag does not exist in the request or is invalid. Add the html <body> tag inside the <html> tag. The <body> tag is required to display HTML content."), 
            new ApiErrorData(223, "The body is missing in the attachments ‘content’ or the void is transferred. Add the ‘content’ and specify a value for it."), 
            new ApiErrorData(224, "Substitution name should contain only latin characters, numbers, “_” character and start with a letter. Make sure the substitution name is passed correctly."), 
            new ApiErrorData(225, "No right for template engine ‘none’. Try contacting support."), 
            new ApiErrorData(226, "Value of ‘track_links’ and ‘track_read’ must be equal to 0 for “template_engine”:“none”. Set parameters value equal to 0."), 
            new ApiErrorData(227, "Invalid or non-existent ‘smtp_pool_id’. Please enter a valid ‘smtp_pool_id’ parameter."), 
            new ApiErrorData(303, "Events list contains an unsupported value or the event is not supported. Verify that the event list is entered correctly."), 
            new ApiErrorData(304, "Webhook with the specified URL has not been found. Make sure the URL is passed correctly."), 
            new ApiErrorData(305, "URL is not passed. Make sure the URL is passed correctly."), 
            new ApiErrorData(601, "Template has not been found. Check the passed template id."), 
            new ApiErrorData(602, "The template name is missing. Check the passed template name."), 
            new ApiErrorData(603, "Template name passed in the request already belongs to another template. Use another name for this template."), 
            new ApiErrorData(604, "Maximum number of templates has been reached. Delete already created templates to create new ones. The number of templates is limited to 10000."), 
            new ApiErrorData(701, "Cause not found. Invalid reason for blocking email. Please contact support."), 
            new ApiErrorData(901, "Sending is blocked because limit is reached. Each user has a maximum daily limit for sending to prevent abuse. This limit increases automatically in case of good delivery and is reset each night. You can smoothly increase amount of daily sending or you can conact support and ask for manual limit increase."), 
            new ApiErrorData(902, "Sending limit for free tariff is reached. Wait till next day or switch to paid tariff."), 
            new ApiErrorData(903, "On free tariff you can send only to your own domains with confirmed verification record. Please confirm ownership of all domains you want to send emails to or switch tariff to the paid one."), 
            new ApiErrorData(904, "Insufficient funds. Credit card transaction failure. Please try another card or contact support to resolve the situation."), 
            new ApiErrorData(905, "You have reached the limit of emails included in your subscription plan. Usually tariff allows paid overage. In this case it’s prohibited, possibly due to unpaid invoice. Please check that all invoices are paid or contact support to solve the problem."), 
            new ApiErrorData(906, "Exceeded the daily email reset limit. You have used the entire available block reset limit. Try it tomorrow or contact support to increase the limit."), 
            new ApiErrorData(908, "Internal error, project owner not found. Please contact support."), 
            new ApiErrorData(1000, "Missing recipient address. Specify the recipient address."), 
            new ApiErrorData(1001, "Invalid recipient address value. Please enter a valid recipient address."), 
            new ApiErrorData(1002, "Missing sender address. Specify the sender address."), 
            new ApiErrorData(1003, "Sender address not verified. Verify the sender domain address."), 
            new ApiErrorData(1004, "Invalid sender address value. Please enter a valid sender address."), 
            new ApiErrorData(1005, "Sender name is too long. The sender name must be shorter. Please correct this value."), 
            new ApiErrorData(1006, "Exceeded the daily limit of the email/subscribe method call. Try to repeat the call the next day."), 
            new ApiErrorData(1100, "Missing domain name. Specify the domain to be verified."), 
            new ApiErrorData(1101, "Invalid domain value. Please enter a valid domain value."), 
            new ApiErrorData(1200, "Missing domain name. Specify the domain for validating."), 
            new ApiErrorData(1201, "Invalid domain value. Please enter a valid domain value."), 
            new ApiErrorData(1202, "Domain is not registered in UniOne. Make a domain/get-dns-records method call."), 
            new ApiErrorData(1301, "Invalid domain value. Specify the domain to be verified."), 
            new ApiErrorData(1302, "Invalid limit value. The value of limit must be an integer in the range of 1 - 100."), 
            new ApiErrorData(1303, "Invalid offset value. The value of offset must be greater than or equal to 0."), 
            new ApiErrorData(1304, "Invalid offset value type. The value of offset must be an integer."), 
            new ApiErrorData(1305, "Invalid limit value type. The value of limit must be an integer."), 
            new ApiErrorData(1400, "Missing domain name. Specify the domain for validating."), 
            new ApiErrorData(1401, "Invalid or non-existent domain. Either you have mistyped the domain name and should correct it or DNS changes have not yet propagated through DNS and you should wait a couple of hours and try again. There should be A, AAAA or MX record for domain."), 
            new ApiErrorData(1402, "Domain is not registered in UniOne. Please call domain/get-dns-records method for domain to be registered."), 
            new ApiErrorData(1506, "Error in ‘headers’ field. This value should have object type. Please check your JSON and use object for ‘headers’ field, not array or string or whatever."), 
            new ApiErrorData(1507, "Error in ‘headers’ field. This container should contain over 50 elements. Please limit ‘headers’ to no more than 50 elements."), 
            new ApiErrorData(1508, "Error in ‘template_id’ field. There is no template with this ID. Make sure the template ID is correct."), 
            new ApiErrorData(1509, "Error in ‘body’ field. This value should have object type. Please check your JSON and use object for ‘body’ field, not array or string or whatever."), 
            new ApiErrorData(1510, "Error in ‘body.html’ field. The value should have a string type. Use string type for ‘body.html’ parameter."), 
            new ApiErrorData(1511, "Error in ‘body.plaintext’ field. The value should have a string type. Use string type for ‘body.plaintext’ parameter."), 
            new ApiErrorData(1512, "Error in ‘body.amp’ field. The value should have a string type. Use string type for ‘body.amp’ parameter."), 
            new ApiErrorData(1516, "Error in ‘body.html’ field. Substitutions contain invalid values. Check the correct substitutions in the ‘body.html’ field."), 
            new ApiErrorData(1517, "Error in ‘body.plaintext’ field. Substitutions contain invalid values. Check the correct substitutions in the ‘body.plaintext’ field."), 
            new ApiErrorData(1518, "Error in ‘body.amp’ field. Substitutions contain invalid values. Check the correct substitutions in the ‘body.amp’ field."), 
            new ApiErrorData(1519, "Error in ‘reply_to’ field. The value should have a string type. Use string type for ‘reply_to’ parameter."), 
            new ApiErrorData(1520, "Error in ‘reply_to’ field. Invalid email. Check if the email is correct."), 
            new ApiErrorData(1521, "Error in ‘from_name’ field. The value should have a string type. Use string type for ‘from_name’ parameter."), 
            new ApiErrorData(1522, "Error in ‘subject’ field. The value should have a string type. Use string type for ‘subject’ parameter."), 
            new ApiErrorData(1523, "Error in ‘template_engine’ field. One of the two properties [‘velocity’ or ‘simple’] is required. Please pass only one of the two parameters: either ‘velocity’ or ‘simple’."), 
            new ApiErrorData(1524, "Error in ‘recipients’ field. This container should contain over 500 elements. Please limit ‘recipients’ to no more than 500 elements."), 
            new ApiErrorData(1525, "Error in ‘options.send_at’ field. Make sure the date and time of the scheduled sending is no more than 24 hours in advance."), 
            new ApiErrorData(1526, "Error in ‘headers[“X-UNIONE-Template-Engine”]’ field. Invalid value, headers[“X-UNIONE-Template-Engine”] could be one of ‘velocity’ or ‘simple’. Please pass only one of the two parameters: either ‘velocity’ or ‘simple’."), 
            new ApiErrorData(1527, "Error in ‘headers[“X-UNIONE-Global-Language”]’ field. Language is not allowed. Please pass only one of ‘ru’, ‘en’, ‘ua’, ‘be’, ‘es’, ‘fr’, ‘pl’, ‘de’, ‘pt’, ‘it’ values."), 
            new ApiErrorData(1528, "Error in ‘global_language’ field. Language is not allowed. Please pass only one of ‘ru’, ‘en’, ‘ua’, ‘be’, ‘es’, ‘fr’, ‘pl’, ‘de’, ‘pt’, ‘it’ values."), 
            new ApiErrorData(1529, "Error in ‘options.send_at’ field. This value should be greater thancurrent time. Set parameter value greater than current time."), 
            new ApiErrorData(1530, "Error in ‘options.send_at’ field. This value should be of type string or this value is not a valid datetime. Use string type for ‘options.send_at’ parameter. Make sure the datetime is passed correctly."), 
            new ApiErrorData(1532, "This collection should contain 4 elements or less. Please limit tags to no more than 4 elements."), 
            new ApiErrorData(1533, "Error in ‘tags’ field. You can not create any more tags. Max tags number is 10000. Delete already created tags to create new ones. The number of tags is limited to 10000."), 
            new ApiErrorData(1534, "One or more tags is too long, max. 50 characters. The tags must be shorter. Please correct this value."), 
            new ApiErrorData(1535, "One or more tags contains invalid symbols. Make sure the tags is passed correctly."), 
            new ApiErrorData(1537, "Error in ‘bypass_global’ field. ‘bypass_global’ should be equal to 1. Set parameter value to 1."), 
            new ApiErrorData(1538, "Error in ‘bypass_unsubscribed’ field. ‘bypass_unsubscribed’ usage is prohibited without ‘allow_skip_unsubscribe’ flag. contact support to set the flag."), 
            new ApiErrorData(1539, "Error in ‘bypass_complained’ field. ‘bypass_complained’ usage is prohibited without ‘allow_skip_unsubscribe’ flag. contact support to set the flag."), 
            new ApiErrorData(1540, "Error in ‘metadata’ field. The maximum allowable ‘metadata’ size is 4000 bytes. Metadata value size should less than 4000 bytes."), 
            new ApiErrorData(1541, "Error in ‘global_metadata’ field. The maximum allowable ‘global_metadata’ size is 4000 bytes. Metadata value size should less than 4000 bytes."), 
            new ApiErrorData(1542, "Error in ‘metadata and global_metadata’ field. The maximum allowable ‘global_metadata’ and ‘metadata’ size is 4000 bytes. Metadata value size should less than 4000 bytes."), 
            new ApiErrorData(1543, "Error in ‘global_metadata.campaign_id’ field. This value should be of type string. Use string type for ‘global_metadata.campaign_id’ parameter."), 
            new ApiErrorData(1544, "Error in ‘metadata.campaign_id’ field. This value should be of type string. Use string type for ‘metadata.campaign_id’ parameter."), 
            new ApiErrorData(1545, "Error in ‘metadata.campaign_id’ field. Value ’ ’ is not a valid number or uuid. Make sure the ‘metadata.campaign_id’ is passed correctly."), 
            new ApiErrorData(1546, "Error in ‘subject’ field. Substitutions contain invalid values. Check the correct substitutions in the ‘subject’ field."), 
            new ApiErrorData(1547, "Error in ‘from_name’ field. Substitutions contain invalid values. Check the correct substitutions in the ‘from_name’ field."), 
            new ApiErrorData(1548, "Error in ‘unsubscribe_url’ field. The value should have a string type. Use string type for ‘unsubscribe_url’ parameter."), 
            new ApiErrorData(1549, "Error in ‘unsubscribe_url’ field. Substitutions contain invalid values. Check the correct substitutions in the ‘unsubscribe_url’ field."), 
            new ApiErrorData(1550, "Error in ‘options’ field. The value should have an object type. Use object type for the ‘options’ parameter."), 
            new ApiErrorData(1551, "Error in ‘metadata or global_metadata collection’ field. The value parameter must be a string. Use string type for ‘metadata’ and ‘global_metadata’ parameters."), 
            new ApiErrorData(1601, "1701; Error in the ‘project’ field. Project section is absent. Correct JSON structure."), 
            new ApiErrorData(1602, "1702; Error in the ‘name’ field. This value should not be blank. Use non-blank name."), 
            new ApiErrorData(1603, "1703; Error in the ‘name’ field. It should have ‘string’ type. Use string type for ‘name’ parameter."), 
            new ApiErrorData(1604, "1704; Error in the ‘name’ field. This value is too long. It should have 255 characters or less. Use shorter name."), 
            new ApiErrorData(1605, "1705; Error in the ‘name’ field. Project with such a name already exists. Use unique project name or delete existing project first."), 
            new ApiErrorData(1701, "Error in the ‘project’ field. Project section is absent. Correct JSON structure."), 
            new ApiErrorData(1702, "Error in the ‘name’ field. This value should not be blank. Use non-blank name."), 
            new ApiErrorData(1703, "Error in the ‘name’ field. It should have ‘string’ type. Use string type for ‘name’ parameter."), 
            new ApiErrorData(1704, "Error in the ‘name’ field. This value is too long. It should have 255 characters or less. Use shorter name."), 
            new ApiErrorData(1705, "Error in the ‘name’ field. Project with such a name already exists. Use unique project name or delete existing project first."), 
            new ApiErrorData(1606, "Error in the ‘send_enabled’ field. This value should be of type bool. Set parameter value to true or false only."), 
            new ApiErrorData(1607, "Error in ‘custom_unsubscribe_url_enabled’ field. This value should be of type bool. Set parameter value to true or false only."), 
            new ApiErrorData(1608, "Forbidden to use field ‘custom_unsubscribe_url_enabled’. Please contact support."), 
            new ApiErrorData(1609, "Error in ‘country’ field. This value should be of type string. Use string type for ‘country’ parameter."), 
            new ApiErrorData(1610, "Error in ‘country’ field. This value is not a valid country. Make sure the ISO-3166 alpha-2 country code is passed correctly."), 
            new ApiErrorData(1611, "Error in ‘backend_domain_id’ field. This value should be of type int. Use int type for ‘backend_domain_id’ parameter."), 
            new ApiErrorData(1612, "Error in ‘backend_domain_id’ field. The backend domain does not belong to the user. Please enter a valid ‘backend_domain_id’ parameter."), 
            new ApiErrorData(1613, "Error in ‘backend_domain_id’ field. Backend domain is not active. Please enter a valid ‘backend_domain_id’ parameter."), 
            new ApiErrorData(1711, "Forbidden to use field ‘custom_unsubscribe_url_enabled’. Please contact support."), 
            new ApiErrorData(1716, "Error in ‘country’ field. This value should be of type string. Use string type for ‘country’ parameter."), 
            new ApiErrorData(1717, "Error in ‘country’ field. This value is not a valid country. Make sure the ISO-3166 alpha-2 country code is passed correctly."), 
            new ApiErrorData(1718, "Error in ‘backend_domain_id’ field. This value should be of type int. Use int type for ‘backend_domain_id’ parameter."), 
            new ApiErrorData(1719, "Error in ‘backend_domain_id’ field. The backend domain does not belong to the user. Please enter a valid ‘backend_domain_id’ parameter."), 
            new ApiErrorData(1720, "Error in ‘backend_domain_id’ field. Backend domain is not active. Please enter a valid ‘backend_domain_id’ parameter."), 
            new ApiErrorData(1706, "Error in ‘project_api_key’ field. One of the two properties [‘project_api_key’ or ‘project_id’] is required. Don’t forget to send either project_id or project_api_key."), 
            new ApiErrorData(1707, "Error in the ‘project_api_key’ field. Project not found. Use correct project_api_key. You can get a list of projects with their keys with project/list method."), 
            new ApiErrorData(1802, "Error in the ‘project_api_key’ field. Project not found. Use correct project_api_key. You can get a list of projects with their keys with project/list method."), 
            new ApiErrorData(1708, "Error in the ‘project_api_key’ field. The value should have a string type. Use string type for ‘project_api_key’."), 
            new ApiErrorData(1709, "Error in the ‘send_enabled’ field. The value should have a bool type. Set parameter value to true or false only."), 
            new ApiErrorData(1710, "Error in ‘custom_unsubscribe_url_enabled’ field. The value should have a bool type. Set parameter value to true or false only."), 
            new ApiErrorData(1712, "Error in ‘project_id’ field. This value should be of type string. Please use string type for project_id field."), 
            new ApiErrorData(1713, "Error in ‘project_api_key’ field. One of the two properties [‘project_api_key’ or ‘project_id’] must be empty. Please pass only one of the two parameters: either project_id or project_api_key, not both."), 
            new ApiErrorData(1714, "Error in ‘project_id’ field. Project with ID:‘NNNN’ not exists. Project id is invalid. Maybe it was deleted or never existed?"), 
            new ApiErrorData(1715, "Error in ‘project_id’ field. This value is not valid. Please check that you pass the project_id you have received by calling project/create method."), 
            new ApiErrorData(1805, "Error in ‘project_id’ field. This value should be of type string. Please use string type for project_id field."), 
            new ApiErrorData(1804, "Error in ‘project_api_key’ field. One of the two properties [‘project_api_key’ or ‘project_id’] must be empty. Please pass only one of the two parameters: either project_id or project_api_key, not both."), 
            new ApiErrorData(1806, "Error in ‘project_id’ field. Project with ID:‘NNNN’ not exists. Project id is invalid. Maybe it was deleted or never existed?"), 
            new ApiErrorData(1807, "Error in ‘project_id’ field. This value is not valid. Please check that you pass the project_id you have received by calling project/create method."), 
            new ApiErrorData(1905, "Error in ‘project_id’ field. This value should be of type string. Please use string type for project_id field."), 
            new ApiErrorData(1801, "Error in ‘project_api_key’ field. One of the two properties [‘project_api_key’ or ‘project_id’] is required. Don’t forget to send either project_id or project_api_key."), 
            new ApiErrorData(1803, "Error in the ‘project_api_key’ field. The value should have a string type. Use string type for ‘project_api_key’."), 
            new ApiErrorData(1902, "Error in the ‘project_api_key’ field. The value should have a string type. Use string type for ‘project_api_key’."), 
            new ApiErrorData(1904, "Error in ‘project_id’ field. This value is not valid. The value should contain digits only. Use correct numbers-only format for ‘project_id’."), 
            new ApiErrorData(2306, "Error in ‘recipients’ field. This value should not be blank. Make sure the ‘recipients’ is passed."), 
            new ApiErrorData(2307, "Error in ‘recipients’ field. This value should be of type string. Use string type for ‘recipients’ parameter."), 
            new ApiErrorData(2500, "Error in ‘editor_type’ field. ‘html’ is required. Make sure the ‘editor_type’ field is passed ‘html’."), 
            new ApiErrorData(2501, "The template was created in a visual editor. Make sure the template is created in HTML editor."), 
            new ApiErrorData(2502, "Error in ‘editor_type’ field. This value should not be blank. Pass ‘html’ in ‘editor_type’ field."), 
            new ApiErrorData(2503, "Error in ‘id’ field. There is no template with this ID. Make sure the template ID is correct."), 
            new ApiErrorData(2504, "Error in ‘headers’ field. This value should have object type. Please check your JSON and use object for ‘headers’ field, not array or string or whatever."), 
            new ApiErrorData(2505, "Error in ‘headers’ field. This container should contain 50 elements or less. Please limit headers to no more than 50 elements."), 
            new ApiErrorData(2514, "Error in ‘reply_to’ field. This value should be of type string. Use string type for ‘reply_to’ parameter."), 
            new ApiErrorData(2515, "Error in ‘reply_to’ field. This value is not a valid email address. Check if the email is correct."), 
            new ApiErrorData(2516, "Error in ‘template_engine’ field. One of the two properties [‘velocity’ or ‘simple’] is required. Please pass only one of the two parameters: either ‘velocity’ or ‘simple’."), 
            new ApiErrorData(2517, "Error in ‘subject’ field. This value should be of type string. Use string type for ‘subject’ parameter."), 
            new ApiErrorData(2518, "Error in ‘subject’ field. Substitutions contain invalid values. Check the correct substitutions in the ‘subject’ field."), 
            new ApiErrorData(2519, "Error in ‘from_name’ field. This value should be of type string. Use string type for ‘from_name’ parameter."), 
            new ApiErrorData(2520, "Error in ‘from_name’ field. Substitutions contain invalid values. Check the correct substitutions in the ‘from_name’ field."), 
            new ApiErrorData(2600, "Error in ‘limit’ field. This value should be greater than or equal to 0. Set parameter value greater than or equal to 0."), 
            new ApiErrorData(2601, "Error in ‘limit’ field. This value should be of type int. Use int type for ‘limit’ parameter."), 
            new ApiErrorData(2602, "Error in ‘offset’ field. This value should be greater than or equal to 0. Set parameter value greater than or equal to 0."), 
            new ApiErrorData(2603, "Error in ‘offset’ field. This value should be of type int. Use int type for ‘offset’ parameter."), 
            new ApiErrorData(2700, "Error in ‘url’ field. This value should be of type string. Use string type for ‘url’ parameter."), 
            new ApiErrorData(2701, "Error in ‘url’ field. This value should not be blank. Make sure the URL is passed."), 
            new ApiErrorData(2702, "Error in ‘offset’ field. This value should be greater than or equal to 0. Set parameter value greater than or equal to 0."), 
            new ApiErrorData(2703, "Error in ‘eventFormat’ field. The value you selected is not a valid choice. Use format ‘json_post’ or ‘json_post_gzip’ only."), 
            new ApiErrorData(2704, "Error in ‘deliveryInfo’ field. ‘delivery_info’ value should be 1\0 either true\false. Set parameter ‘delivery_info’ value to 1\0 either true\false."), 
            new ApiErrorData(2705, "Error in ‘singleEvent’ field. ‘single_event’ value should be 1\0 either true\false. Set parameter ‘single_event’ value to 1\0 either true\false."), 
            new ApiErrorData(2706, "Error in ‘maxParallel’ field. This value should be of type int. Use int type for ‘maxParallel’ parameter."), 
            new ApiErrorData(2707, "Error in ‘maxParallel’ field. This value should be between 5 and 100. Use a valid value of 5 to 100."), 
            new ApiErrorData(2708, "Error in ‘events’ field. This value should be of type array. Use array type for ‘events’ parameter."), 
            new ApiErrorData(2709, "Error in ‘events’ field. This value should not be blank. Use non-blank events."), 
            new ApiErrorData(2710, "Error in ‘events’ field. Field ‘email_status’ is required. Add ‘email_status’ parameter."), 
            new ApiErrorData(2711, "Error in ‘email_status’ field. This value ‘test’ is not a valid email_status. Add valid email statuses in the value."), 
            new ApiErrorData(2712, "Error in ‘spam_block’ field. This value ‘test’ is not a valid spam_block. Add valid spam blocking events in the value."), 
            new ApiErrorData(2713, "Error in ‘url’ field. Webhook domain name not found. Make sure the domain is passed correctly."), 
            new ApiErrorData(2714, "Error in ‘status’ field. Invalid value, status could be one of ‘active’ or ‘disabled’. Set status ‘active’ or ‘disabled’."), 
            new ApiErrorData(2715, "Error in ‘status’ field. This value should be of type string. Use string type for ‘status’ parameter."), 
            new ApiErrorData(2800, "Error in ‘name’ field. This value should not be blank. Make sure the ‘name’ is passed."), 
            new ApiErrorData(2801, "Error in ‘name’ field. The value should have a string type. Use string type for ‘name’ parameter."), 
            new ApiErrorData(2802, "Error in ‘type’ field. The value should have a string type. Use string type for ‘type’ parameter."), 
            new ApiErrorData(2803, "Error in ‘content’ field. The value should have a string type. Use string type for ‘content’ parameter."), 
            new ApiErrorData(2804, "The size of the ‘content’ field must not exceed 7MB. Reduce the size of the ‘content’ field to 7MB (9786710 bytes in base64)."), 
            new ApiErrorData(2900, "Error in ‘email’ field. This value should not be blank. Make sure the email is passed."), 
            new ApiErrorData(2901, "Error in ‘email’ field. This value should be of type string. Use string type for ‘email’ parameter."), 
            new ApiErrorData(2902, "Error in ‘email’ field. This value is not a valid email address. Verify that email is entered correctly."), 
            new ApiErrorData(3000, "Error in ‘email’ field. This value should not be blank. Make sure the email is passed."), 
            new ApiErrorData(3001, "Error in ‘email’ field. This value should be of type string. Use string type for ‘email’ parameter."), 
            new ApiErrorData(3002, "Error in ‘email’ field. This value is not a valid email address. Verify that email is entered correctly."), 
            new ApiErrorData(3100, "Error in ‘email’ field. This value should not be blank. Make sure the email is passed."), 
            new ApiErrorData(3101, "Error in ‘email’ field. This value should be of type string. Use string type for ‘email’ parameter."), 
            new ApiErrorData(3102, "Error in ‘email’ field. This value is not a valid email address. Verify that email is entered correctly."), 
            new ApiErrorData(2903, "Error in ‘all_projects’ field. This value should be of type bool. Set parameter value to true or false only."), 
            new ApiErrorData(3003, "Error in ‘email’ field. Email doesn’t exist. Email was not found in the suppression list."), 
            new ApiErrorData(3004, "Error in ‘email’ field. Email cannot be deleted. Email cannot be removed from the suppression list. Probably because of the severe reason like ‘blocked’."), 
            new ApiErrorData(3103, "Error in ‘cause’ field. This value should not be blank. Make sure the ‘cause’ is passed."), 
            new ApiErrorData(3104, "Error in ‘cause’ field. This value should be of type string. Use string type for ‘country’ parameter."), 
            new ApiErrorData(3105, "Error in ‘cause’ field. Cause ‘test’ not allowed. Please pass only one of the available values."), 
            new ApiErrorData(3200, "Error in ‘cause’ field. This value should be of type string. Use string type for ‘country’ parameter."), 
            new ApiErrorData(3201, "Error in ‘cause’ field. Cause ‘test’ not allowed. Please pass only one of the available values."), 
            new ApiErrorData(3106, "Error in ‘created’ field. This value should be of type string. Use string type for ‘created’ parameter."), 
            new ApiErrorData(3107, "Error in ‘created’ field. This value is not a valid datetime. Make sure the datetime is passed correctly."), 
            new ApiErrorData(3202, "Error in ‘source’ field. This value should be of type string. Use string type for ‘source’ parameter."), 
            new ApiErrorData(3203, "Error in ‘source’ field. Source ‘test’ not allowed. Please pass only one of the available values."), 
            new ApiErrorData(3204, "Error in ‘start_time’ field. This value should be of type string. Use string type for ‘start_time’ parameter."), 
            new ApiErrorData(3205, "Error in ‘start_time’ field. This value is not a valid datetime. Make sure the datetime is passed correctly."), 
            new ApiErrorData(3206, "Error in ‘cursor’ field. This value should be of type string. Use string type for ‘cursor’ parameter."), 
            new ApiErrorData(3207, "Error in ‘cursor’ field. Cursor ‘test’ not allowed. Please pass only one of the available values."), 
            new ApiErrorData(3208, "Error in ‘limit’ field. This value should be of type int. Use int type for ‘limit’ parameter."), 
            new ApiErrorData(3209, "Error in ‘limit’ field. This value should be greater than or equal to 0. Set parameter value greater than or equal to 0."), 
            new ApiErrorData(3300, "Error in ‘start_time’ field. This value should not be blank. Make sure the ‘start_time’ is passed."), 
            new ApiErrorData(3301, "Error in ‘start_time’ field. This value is not a valid datetime. Make sure the datetime is passed correctly."), 
            new ApiErrorData(3302, "Error in ‘end_time’ field. This value is not a valid datetime. Make sure the datetime is passed correctly."), 
            new ApiErrorData(3303, "Error in ‘limit’ field. This value should be positive. Set parameter value greater than or equal to 0."), 
            new ApiErrorData(3304, "Error in ‘format’ field. Incorrect value of the event dump file format. Use ‘csv’ or ‘csv_gzip’ format only."), 
            new ApiErrorData(3305, "Error in ‘delimiter’ field. Incorrect value of the event dump file delimiter. Use ‘delimiter’ ‘;’ or ‘,’ only."), 
            new ApiErrorData(3308, "Error in ‘all_projects’ field. The user does not have the required roles. Projects methods are disabled by default. To enable them,contact support."), 
            new ApiErrorData(3309, "User can have no more than 10 event dumps at a time. Delete already created dumps to create new ones. The number of dumps is limited to 10."), 
            new ApiErrorData(3310, "Error in ‘start_time’ field. The interval start date cannot be earlier than ‘$time’. Make sure ‘start_time’ is in the allowed range."), 
            new ApiErrorData(3311, "Error in ‘limit’ field. This value should be of type integer. Use int type for ‘limit’ parameter."), 
            new ApiErrorData(3312, "Error in ‘delimiter’ field. This value should be of type string. Use string type for ‘delimiter’ parameter."), 
            new ApiErrorData(3313, "Error in ‘format’ field. This value should be of type string. Use string type for ‘format’ parameter."), 
            new ApiErrorData(3400, "Error in ‘filter’ field. This value should be of type object. Please check your JSON and use object for ‘filter’ field, not array or string or whatever."), 
            new ApiErrorData(3401, "Error in ‘filter.job_id’ field. This value should be of type string. Use string type for ‘filter.job_id’ parameter."), 
            new ApiErrorData(3402, "Error in ‘filter.status’ field. This value should be of type string. Use string type for ‘filter.status’ parameter."), 
            new ApiErrorData(3403, "Error in ‘filter.status’ field. Status ‘dfdfs’ is invalid. Please enter a valid ‘filter.status’ parameter."), 
            new ApiErrorData(3404, "Error in ‘filter.email’ field. This value should be of type string. Use string type for ‘filter.email’ parameter."), 
            new ApiErrorData(3405, "Error in ‘filter.email’ field. This value ‘ewrewrew@dsfdfdds’ is not a valid email address. Check if the email is correct."), 
            new ApiErrorData(3406, "Error in ‘filter.email_from’ field. This value should be of type string. Use string type for ‘filter.email_from’ parameter."), 
            new ApiErrorData(3407, "Error in ‘filter.email_from’ field. This value ‘bitko82@gmailcom’ is not a valid email address. Check if the email is correct."), 
            new ApiErrorData(3408, "Error in ‘filter.domain’ field. This value should be of type string. Use string type for ‘filter.domain’ parameter."), 
            new ApiErrorData(3409, "Error in ‘filter.domain’ field. This value ‘test’ is not a valid domain. Please enter a valid domain value."), 
            new ApiErrorData(3410, "Error in ‘filter.domain’ field. Domain ‘gmail.com’ different from the domain in the email. Make sure the domain is passed correctly."), 
            new ApiErrorData(3411, "Error in ‘filter.delivery_status’ field. This value should be of type string. Use string type for ‘filter.delivery_status’ parameter."), 
            new ApiErrorData(3412, "Error in ‘filter.delivery_status’ field. Status ‘63’ is invalid. Please enter a valid ‘filter.delivery_status’ parameter."), 
            new ApiErrorData(3413, "Error in ‘filter.campaign_id’ field. This value should be of type string. Use string type for ‘filter.campaign_id’ parameter."), 
            new ApiErrorData(3414, "Error in ‘filter.campaign_id’ field. Value ‘340282366920938463463374607431768211255999’ is invalid number. The data in request should be no more than 128 bit."), 
            new ApiErrorData(3500, "Error in ‘dump_id’ field. This value should not be blank. Make sure the ‘dump_id’ is passed."), 
            new ApiErrorData(3501, "Error in ‘dump_id’ field. This is not a valid UUID. Make sure the ‘dump_id’ is passed correctly."), 
            new ApiErrorData(3502, "Error in ‘dump_id’ field. Event dump with ID ‘NNNN’ does not exist. Dump ID is invalid. Maybe it was deleted or never existed? "), 
            new ApiErrorData(3600, "Error in ‘dump_id’ field. This value should not be blank. Make sure the ‘dump_id’ is passed."), 
            new ApiErrorData(3601, "Error in ‘dump_id’ field. This is not a valid UUID. Make sure the ‘dump_id’ is passed correctly."), 
            new ApiErrorData(3602, "Error in ‘dump_id’ field. Event dump with ID ‘NNNN’ does not exist. Dump ID is invalid. Maybe it was deleted or never existed? "), 
            new ApiErrorData(3700, "This value should not be blank. Make sure the ‘tag_id’ is passed."), 
            new ApiErrorData(3701, "This value should be of type int. Use int type for ‘tag_id’ parameter."), 
            new ApiErrorData(3800, "Error in ‘email’ field. The maximum number of concurrent requests should not exceed 4. Reduce the the numbers of concurrent requests to 4."), 
            new ApiErrorData(3801, "Error in ‘email’ field. This value should not be blank. Make sure the email is passed."), 
            new ApiErrorData(3802, "Error in ‘email’ field. This value should be of type string. Use string type for ‘email’ parameter."), 
            new ApiErrorData(3803, "Error in ‘email’ field. Exceeded the daily limit of the email-validation/single method call. Try to repeat the call the next day.")
        };

        return errorCodes;
    }
}